define({
	BackEnd:{
		Ip:'http://localhost:11919/',
		Desks:'api/Restaurant/AllDesksWithAccount',
		Menus:'api/Menu/FullinRestaurant',
		Login:'api/Authenticated',/*登录*/
		Members:'api/Members/GetMembers',/*获取会员信息*/
		SetMPassword:'api/Members/MberPassword',/*设置会员密码*/
		MemberState:'api/Members/SetMemberState',/*会员状态*/
		Consume:'api/Members/ConsumPtion',/*获取消费信息*/
		Recharge:'api/Members/RechargeAt',/*获取充值信息*/
		AddReCharge:'api/Members/AddRecharge',/*会员卡充值*/
		Rebates:'api/Members/Rebates',/*返现*/
		MembersType:'api/Members/MemberClassify',/*会员类型*/
		AddMemberType:'api/Members/AddMemberClassify',/*增加会员类型*/
		EditMembersType:'api/Members/UpdateMemberClassify',/*编辑会员类型*/
		DeleteMembersType:'api/Members/DeleteMemberClassify',/*删除会员类型*/
		GetMemberCardId:'api/Members/GetMemberCardId',/*获取会员卡id*/
		AddMembers:'api/Members/AddMembers',/*新建会员*/
		EditMembers:'api/Members/UpdateMembers',/*编辑会员*/
		Discount:'api/Dis/DiscountAt',/*获取折扣信息*/
		Adddiscount:'api/Dis/AddDiscount',/*增加折扣*/
		Editdiscount:'api/Dis/UpdateDiscount',/*编辑折扣*/
		Deletediscount:'api/Dis/SetDiscountState',/*删除折扣*/
		MenuClassify:'api/Menu/GetMenuClassifies',/*获取菜单分类*/
		AddMenuClassify:'api/Menu/AddMenuClassify',/*增加菜单分类*/
		EditMenuClassify:'api/Menu/UpdateMenuClassify',/*编辑菜单分类*/
		DeleteMenuClassify:'api/Menu/DeleteMenuClassify',/*删除菜单分类*/
		AllMenus:'api/Menu/GetAllMenus',/*获取菜品*/
		AddMenus:'api/Menu/AddMenu',/*添加菜品*/
		Editmenus:'api/Menu/UpdateMenu',/*编辑菜品*/
		Deletemenus:'api/Menu/DeleteMenu',/*删除菜品*/
		GetDesks:'api/Restaurant/GetAllDesks',/*获取餐桌信息*/
		AddDesks:'api/Restaurant/AddDesk',/*新建餐桌*/
		EditDesks:'api/Restaurant/UpdateDesk',/*编辑餐桌*/
		DeleteDesks:'api/Restaurant/DeleteDesk',/*删除餐桌*/
		GetEmployee:'api/User/GetAllWorkers',/*获取员工信息*/
		AddEmployee:'api/User/AddWorker',/*增添新员工*/
		EditEmployee:'api/User/UpdateWorker',/*修改员工信息*/
	    DeleteEmployee:'api/User/FixWorkerbyId',/*改变员工状态及删除员工*/
	    DailyTurnover:'api/Revenue/DailyTurnover',/*获取当日营业额*/
	    DailyHotMenus:'api/Revenue/DailyHotMenus',/*获取当日热门菜品*/
	    DailyBillsss:'api/Revenue/DailyBills',/*获取当日账单*/
	    TurnoverExcel:'api/Revenue/RanRevenuesExcl',/*营业额下载*/
	    TurnoverEmail:'api/Revenue/RanRevenuesEmail',/*营业额邮件*/
	    BackOrder:'api/Order/BackOrderMenu',/*退单*/
	    OperAnalysis:'api/Revenue/OperationAnalysis', /*运营分析*/
	    RepeatTable:'api/Revenue/RepeatTable',/*翻台数据*/
	    SetRepeatTime:'api/Revenue/SetRepeatTime',/*修改翻台时间段*/
	    TurnoverCharts:'api/Revenue/TurnoverDetails',/*营业额详情*/
	    OrderCharts:'api/Revenue/OrderDetails',/*下单情况详情*/
	    //MemberRecordDetails:'api/Revenue/MemberRecordDetails',/*会员详情*/
	    AnalysisTable:'api/Revenue/',/*受欢迎菜品详情、会员消费记录详情*/
		User:'api/User/SearchbyId',
		Restaurant:'api/Restaurant/SearchRestaurantbyId',
		AddOrderBill:'api/Order/OrderwithMenu',/*添加订单*/
		DeskOrder:'api/Bill/SameDayOrderDesk',/*获取当天未清台的账单*/
		DeskOrderSin:'api/Bill/SameDayOrderDeskSin',/*获取当天未清台的账单*/
		OrderDetail:'api/Bill/OrderBill',/*账单详情*/
		UpdateMenuServing:'api/Order/IsOnTable',/*更新是否上菜*/
		Key:'api/key'
	},
	BackEnd_:{
		KeyClient:'api/KeyClient',/*客户端数据加密的秘钥,每天更新一次*/
		AddOrderMenus:'api/Order/AddOrderMenus',/*添加订单的菜品*/
		ClearDesk:'api/Restaurant/CleanDesk',/*清台指定餐桌*/
		DailyBills:'api/Revenue/DeskPaid',/*今日已经完成的订单*/
		SwitchDesk:'api/Order/ChangeDesk',/*转换餐桌*/
		Worker:'api/User/GetAllWorkers',/*获取店铺的所有的服务员*/
		EntireDiscount:'api/Dis/EntireDiscount',/*整单折扣信息*/
		SingleDiscount:'api/Dis/SingleDiscount',/*单品折扣信息*/
		TellDiscount:'api/Dis/TellDiscount',/*管理员折扣信息验证*/
		MangeUser:'api/Dis/MangeUser',/*获取餐厅的管理员*/
		DefaultOrderBill:'api/Bill/DefaultOrderBill',/*获取当前餐桌的未付款的订单*/
		CheckoutOrderBill:'api/Bill/CheckoutOrderBill',/*提交结账订单*/
		CleanRestaurantDesk:'api/Restaurant/CleanRestaurantDesk',/*清理餐厅所有已经付款的餐桌*/
		AuthenticatedUser:'api/AuthenticatedUser',/*验证用户是否登陆过*/
		DeskState:'api/Restaurant/DeskState',/*获取餐桌的Id*/
		GetMember:'api/Members/GetMember',/*查询会员(会员支付)*/
		AuthMemberPass:'api/Members/AuthMemberPass'/*验证会员密码*/
	},
	Common:{
		Key:"",
		KeyClient:"",
		Token:""
	}
})
